[project]
name = "episode5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "omkar", email = "omkar@DESKTOP-LKR8LSJ" }
]
requires-python = ">=3.11"
dependencies = [
    "groq>=1.7.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
]

[project.scripts]
episode5 = "episode5:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
